   - name: Deploy to Neocities
      uses: bcomnes/deploy-to-neocities@v3
      with:
        api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true
        neocities_supporter: true 
        dist_dir: site/
